Repository teracyhq/dev, pull requests merged in 2018-12, with the labels that each got.

#562 @ #561 | fix git double quote
  lib/teracy-dev/location/git_synch.rb
Labels: stag:under-review

#568 @ #558 | should use MIT license instead
  LICENSE
Labels: stag:under-review

#566 #565 | how to add export env var
  docs/getting_started.rst
Labels: stag:under-review

#569 @ #567 | should deprecate logging filter.filtered and use filter.filter instead for consistency
  lib/teracy-dev/logging.rb
  lib/teracy-dev/logging/filter.rb
  lib/teracy-dev/logging/mask_filter.rb
Labels: stag:under-review

#571 @ #570 | should use TeracyDev.init for convention consistence with extensions
  Vagrantfile
  lib/teracy-dev.rb
  lib/teracy-dev/logging.rb
  lib/teracy-dev/logging/acceptor.rb
  lib/teracy-dev/logging/filter.rb
  lib/teracy-dev/logging/mask_filter.rb
  lib/teracy-dev/logging/progname_acceptor.rb
Labels: stag:under-review

#573 @ #572 | should add Location::Manager.add_synch for extension support
  lib/teracy-dev.rb
  lib/teracy-dev/location/git_synch.rb
  lib/teracy-dev/location/manager.rb
  lib/teracy-dev/location/synch.rb
Labels: stag:under-review

#578 @ #559 | should load <teracy-dev-entry>/teracy-dev-ext.rb if avaiable
  lib/teracy-dev/loader.rb
Labels: stag:under-review

#579 @ #574 | Util.override with nil source should return the origin object
  lib/teracy-dev/util.rb
Labels: stag:under-review

#581 @ #580 | use LANG over prefered language
  lib/teracy-dev/location/git_synch.rb
Labels: affected:develop, affected:v0.6.0-a5, comp:location, prio:critical, stag:under-review, type:bug

#583 @ #582 | should release v0.6.0-a6
  CHANGELOG.md
  config.yaml
  docs/conf.py
  lib/teracy-dev/version.rb
Labels: stag:under-review

#584 should update the teracy-dev git remote repos even when location['sync'] is false
  lib/teracy-dev/loader.rb
Labels: affected:develop, affected:v0.6.0-a5, comp:loader, prio:major, stag:under-review, tag:unplanned, type:bug

#585 @ #575 | failed to uninstall plugins with improvement: installation retry, support env_local config for plugin to install/uninstall local or global mode
  lib/teracy-dev/plugin.rb
Labels: stag:under-review
